name: Model Docker Image CI

on:
  push:
    branches: [ main ]
    paths: 
      - model/Dockerfile
  pull_request:
    branches: [ main ]
    paths: model/**
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKER_HUB_PASS }} | docker login -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin

    - name: Build the tagged Docker image
      working-directory: ./model
      run: docker build --tag navn1/atomfinder_skunkworks:model1 .

    - name: Push the tagged Docker image
      run: docker push navn1/atomfinder_skunkworks:model1

